version: '3.9'
services:
  db:
    image: postgres:{{ cookiecutter.__devops_db_version }}
    networks:
      - {{ cookiecutter.devops_farmos_private_network }}-release
    volumes:
      - './release-db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: {{ cookiecutter.__container_image_prefix }}-{{ cookiecutter.farmos_release_version }}:${STACK_PARAM:-latest}
    networks:
      - {{ cookiecutter.devops_farmos_private_network }}-release
    volumes:
      - './release-www:/opt/drupal/web/sites/default'
    ports:
      - '80:80'
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1
      # Enable these for PHPStorm:
      XDEBUG_SESSION: PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost

networks:
  {{ cookiecutter.devops_farmos_private_network }}-release:
    driver: bridge
    name: {{ cookiecutter.devops_farmos_private_network }}-release
