# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
      day: monday
      time: "06:00"
      timezone: US/Eastern
    open-pull-requests-limit: 10
