name: Run tests
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.testing.yml
      MODULE_NAME: {{ cookiecutter.project_slug }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Start containers
        run: docker-compose up -d
      - name: Include module dependencies
        run: |
          docker-compose exec -u www-data -T www composer config --merge --json extra.merge-plugin.include '["web/modules/custom/*/*.json"]'
          docker-compose exec -u www-data -T www composer update
      - name: Run PHP CodeSniffer
        run: docker-compose exec -u www-data -T www phpcs /opt/drupal/web/modules/custom --exclude=DrupalPractice.InfoFiles.NamespacedDependency
      - name: Run PHPUnit tests.
        run: docker-compose exec -u www-data -T www phpunit /opt/drupal/web/modules/custom
      - name: Install farmOS.
        run: docker-compose exec -u www-data -T www bash -c "drush site-install --db-url=pgsql://farm:farm@db/farm farm farm.modules='base'"
      - name: Test installing the module.
        run: docker-compose exec -u www-data -T www bash -c "drush en $MODULE_NAME -y"
