name: Build farmOS Branch CI

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./farmOS

env:
  IMAGE_NAME_PREFIX: {{ cookiecutter.__container_image_prefix }}-{{ cookiecutter.farmos_branch_version }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@{{ cookiecutter.__gha_checkout_version }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@{{ cookiecutter.__gha_docker_docker_metadata_version }}
        with:
          images: |
            {{ "${{ env.IMAGE_NAME_PREFIX }}" }}
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 80:80 {{ "${{ env.IMAGE_NAME_PREFIX }}" }}:latest
          flavor:
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{ "{{is_default_branch}}" }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@{{ cookiecutter.__gha_docker_docker_qemu_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@{{ cookiecutter.__gha_docker_docker_buildx_version }}

      - name: Login to Container Registry
        uses: docker/login-action@{{ cookiecutter.__gha_docker_docker_login_version }}
        with:
          {%- if cookiecutter.container_registry == 'Docker Hub' %}
          username: {{"${{ secrets.DOCKERHUB_USERNAME }}"}}
          password: {{"${{ secrets.DOCKERHUB_TOKEN }}"}}
          {%- endif %}
          {%- if cookiecutter.container_registry == 'GitHub' %}
          registry: ghcr.io
          username: {{"${{ github.actor }}"}}
          password: {{"${{ secrets.GITHUB_TOKEN }}"}}
          {%- endif %}

      - name: Build and push
        uses: docker/build-push-action@{{ cookiecutter.__gha_docker_docker_build_push_version }}
        with:
          platforms: linux/amd64
          context: farmOS/
          file: farmOS/Dockerfile.branch
          push: {{"${{ github.event_name != 'pull_request' }}"}}
          tags: {{"${{ steps.meta.outputs.tags }}"}}
          labels: {{"${{ steps.meta.outputs.labels }}"}}
