name: Deploy Traefik CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to cluster
        uses: kitconcept/docker-stack-deploy@{{ cookiecutter.__gha_docker_stack_version }}
        with:
          registry: "ghcr.io"
          username: {{ "${{ github.actor }}" }}
          password: {{ "${{ secrets.GITHUB_TOKEN }}" }}
          remote_host: {{ "${{ vars.DEPLOY_HOST }}" }}
          remote_port: {{ "${{ vars.DEPLOY_PORT }}" }}
          remote_user: {{ "${{ vars.DEPLOY_USER }}" }}
          remote_private_key: {{ "${{ secrets.DEPLOY_SSH }}" }}
          stack_file: devops/stacks/traefik-swarm.yml
          stack_name: {{ cookiecutter.devops_traefik_stack_name }}
          stack_param: {{ "${{ github.ref_name }}" }}
          env_file: {{ "${{ secrets.ENV_FILE }}" }}
          deploy_timeout: 480
